version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: catalog-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks: [fastfood]

  api:
    build: .
    container_name: catalog-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks: [fastfood]

volumes:
  mongo_data:

networks:
  fastfood:
    external: true
    name: fastfood-net
